version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: postgres
        ports:
            - 5432:5432
    
    pgadmin:
        links:
            - db:db
        image: dpage/pgadmin4
        restart: always
        ports:
          - "5050:80"
        # networks:
        #   - postgres
